BaSP-m2023/juvi-megarocket-server

src/models/Subscription.js, src/validations/subscription.js
Changes on members types in schema and validations, collaboration with @ale-schmidt @lorenzomauro59 @Gonzarey96 @FrancoLelli
=> BaSP-MR-29: Update subscription schema

src/controllers/activity.js, src/controllers/admins.js, src/controllers/class.js, src/controllers/member.js, src/controllers/subscription.js, src/controllers/super-admins.js, src/controllers/trainer.js
With @Gonzarey96 we fixed the problem that in the findByIdAndUpdate method, by default, it ignores the validations in the Model. Adding runValidator: true, validates the model.
=> BaSP-MR-31: Fix update controller

juvi-megarocket-server.postman_collection.json, src/routes/index.js
In collaboration with @WalterArielPavicich
=> BaSP-MR-30: Fix subscription routes

.eslintrc.js, .husky/pre-commit, babel.config.js, jest.config.js, jest.setup.js, package-lock.json, package.json, src/app.js, src/index.js
With @ale-schmidt , @Tilajc , @lorenzomauro59 , @TomasRomanoo, we installed libraries and updated folders structures
=> BaSP-MR-32: Install libraries and update folders

src/controllers/class.js, src/controllers/subscription.js, src/models/Class.js, src/models/Subscription.js
Did this with @Milicerro, @Gonzarey96 and @WalterArielPavicich
=> BaSP-MR-49: Added populate in controllers and modified schemas

src/controllers/subscription.js, src/models/Subscription.js, src/validations/subscription.js
In collaboration with @WalterArielPavicich
=> BaSP-MR-50: Fix class property and fix error in filter by id, in subscription

src/seeds/class.js, src/tests/class.test.js
With @ale-schmidt , we created tests in Class
=> BaSP-MR-41: Put, Delete and Filter tests in Class

src/tests/class.test.js
i changed toBe to toBeFalsy and status 404 to 500 in Class test
=> BaSP-MR-51: Fix tests in Class

src/controllers/class.js, src/tests/class.test.js, src/validations/class.js
Added validation of trainer Id to create in class controller
Added validation of activity Id to create in class controller
Added validation of trainer Id to update in class controller
Added validation of activity Id to update in class controller
Added validation on class validation to check if the trainer id and activity id is a valid mongo Id format
I also needed to change thing on the class test due to the new validations added on the controller, i had to add the trainer and activities seed so there can be loaded on to the mockDB
=> BaSP-MR-61:Server fix classes

package-lock.json, src/controllers/subscription.js, src/tests/subscription.test.js, src/validations/subscription.js
Fix test from subscription server
=> BaSP-MR-63: Server fix Subscriptions

src/controllers/admins.js
Fixed bug from email . now you can editing or creating an admin with any email which is not currently in use.
=> MR-95: bug for email fixed

src/models/Admins.js
fixed an issue with email alert due to misconfiguration
=> MR-102: fixed bug for admin email

src/controllers/member.js, src/models/Member.js, src/seeds/member.js, src/tests/member.test.js, src/validations/member.js
**Changes**
-Model: password added
-Validation: password min(8)-max(12)-required() added
-Controller: password at creation added
-Test: all test involved
=> [FIX] BaSP-MR-91: password attribute added to the member model

src/models/Admins.js, src/models/Member.js, src/models/Super-admin.js, src/models/Trainer.js, src/validations/admins.js, src/validations/member.js, src/validations/super-admins.js, src/validations/trainer.js
Changed the email regex for a new one
Added custom messages for the regex validation
=> BaSP-MR-125:Fix email regex and added custom messages for other regex

src/validations/admins.js, src/validations/member.js, src/validations/super-admins.js, src/validations/trainer.js
Fixed typing errors in trainers, super-admins, members, admins,
Fixed one message for city in members
=> BaSP-MR-126:fix typing errors

package-lock.json, package.json, src/helper/firebase/index.js, src/middlewares/authMiddleware.js, src/models/Admins.js, src/models/Member.js, src/models/Super-admin.js, src/models/Trainer.js
I installed Firebase admin and rearrange the folders.
=> BaSP-MR-154: Firebase Setup

src/controllers/admins.js, src/controllers/auth.js, src/controllers/member.js, src/controllers/super-admins.js, src/controllers/trainer.js, src/models/Admins.js, src/models/Member.js, src/models/Super-admin.js, src/models/Trainer.js
Following the steps of the weekly class I made the new outline requested for the week, it may not be correct, anyway comment or send md.
=> BaSP-MR-161: Finish new scheme 

src/routes/activity.js, src/routes/admins.js, src/routes/class.js, src/routes/member.js, src/routes/trainer.js
The need to recognize a specific role is added to the routes from the server in order to access them
=>  BaSP-MR-158: Apply verifyToken to the server´s routes.

src/routes/member.js
**Changes**
-Verify token removed from addMember route
=> BaSP-MR-176: Change member create route [FIX]

src/controllers/auth.js, src/controllers/super-admins.js, src/middlewares/authMiddleware.js, src/routes/auth.js, src/routes/index.js
Fixing the setting of auth and super-admin routes.
=>  BaSP-MR-178: [FIX] auth routes

src/controllers/admins.js, src/controllers/member.js, src/controllers/super-admins.js, src/controllers/trainer.js, src/routes/admins.js, src/validations/admins.js, src/validations/member.js, src/validations/super-admins.js, src/validations/trainer.js
Passwords can now be edited in ADMIN, MEMBERS, SUPERADMIN and TRAINERS and deleting them makes the same roles inactive in firebase.
=> BaSP-MR-188: Fixed firebase methods 

src/routes/super-admins.js
Problem in the navbar when logging in with superadmin
=> MR-196: solved problem with superadmin routes

src/controllers/admins.js, src/controllers/class.js, src/controllers/member.js, src/controllers/subscription.js, src/controllers/trainer.js, src/routes/admins.js, src/routes/class.js, src/routes/member.js, src/routes/trainer.js
**Changes:**
- Subscription now populates when PUT endpoint success
- Class routes middleware changes: Now members are able to use it
=> [Fix] BaSP-MR-182: Member subscription

src/controllers/admins.js, src/controllers/member.js, src/controllers/subscription.js, src/controllers/trainer.js, src/validations/subscription.js
**Changes:**
- Controller and validations of createSubscription modified
=> BaSP-MR-220: Change the create validation and controller

src/controllers/member.js, src/controllers/subscription.js, src/controllers/trainer.js
**Changes**
- Validations
- member, admin and trainer messages
=> [Fix] BaSP-MR-222: Subs modifications
